### ISSUE TITLE
When will the data be open-sourced?

### ISSUE THREAD

**Issue by ApolloRay** [YuxiangChai/AMEX#1]
This really is an interesting project. I’m eager to know when the data will be open-sourced, or if you could possibly send me the link privately?

**Comment by YuxiangChai** [comment]
please check the huggingface link provided in the site

**Comment by ApolloRay** [comment]
<img width="1333" alt="截屏2024-07-29 11 06 02" src="https://github.com/user-attachments/assets/7b3a5dc6-b812-4c81-902a-369bdff6887e">

**Comment by YuxiangChai** [comment]
working on it... Use this link for now [https://huggingface.co/datasets/Yuxiang007/AMEX/tree/main](https://huggingface.co/datasets/Yuxiang007/AMEX/tree/main)
